name: dota_v2_pepe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter: 
    sdk: flutter
  material_color_generator: ^1.1.0
  dio: ^5.1.1
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  # flutter_native_splash: ^2.2.19

  
dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter_native_splash:
  andriod: true
  ios: true
  web: false

  color: '#1E2328'
  
  android_12:
    color: '#1E2328'
    image: assets/images/logo.png
    
flutter: 
  uses-material-design: true
  assets:
    - assets/images/